#Ê±ÐòÔ¼Êø
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sys_clk]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property PACKAGE_PIN T14 [get_ports {da_data[9]}]
set_property PACKAGE_PIN T15 [get_ports {da_data[8]}]
set_property PACKAGE_PIN Y17 [get_ports {da_data[7]}]
set_property PACKAGE_PIN Y16 [get_ports {da_data[6]}]
set_property PACKAGE_PIN T16 [get_ports {da_data[5]}]
set_property PACKAGE_PIN U17 [get_ports {da_data[4]}]
set_property PACKAGE_PIN V17 [get_ports {da_data[3]}]
set_property PACKAGE_PIN V18 [get_ports {da_data[2]}]
set_property PACKAGE_PIN T17 [get_ports {da_data[1]}]
set_property PACKAGE_PIN R18 [get_ports {da_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk]
set_property PACKAGE_PIN W16 [get_ports da_clk]

set_property PACKAGE_PIN W18 [get_ports {da_data1[9]}]
set_property PACKAGE_PIN W19 [get_ports {da_data1[8]}]
set_property PACKAGE_PIN R16 [get_ports {da_data1[7]}]
set_property PACKAGE_PIN R17 [get_ports {da_data1[6]}]
set_property PACKAGE_PIN W20 [get_ports {da_data1[5]}]
set_property PACKAGE_PIN V20 [get_ports {da_data1[4]}]
set_property PACKAGE_PIN P18 [get_ports {da_data1[3]}]
set_property PACKAGE_PIN N17 [get_ports {da_data1[2]}]
set_property PACKAGE_PIN P19 [get_ports {da_data1[1]}]
set_property PACKAGE_PIN N18 [get_ports {da_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk1]
set_property PACKAGE_PIN P16 [get_ports da_clk1]
