# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/ZYNQ/ZYNQ7020/7010/RLT/19_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0_1/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
