# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.cache/wt [current_project]
set_property parent.project_path E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/lcd/clk_div.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/touch/i2c_dri_m.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/lcd/lcd_display.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/lcd/lcd_driver.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/lcd/lcd_rgb_char.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/lcd/rd_id.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/touch/touch_dri.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/touch/touch_top.v
  E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/new/top_lcd_touch.v
}
read_ip -quiet e:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/constrs_1/new/top_lcd_touch.xdc
set_property used_in_implementation false [get_files E:/LCD_TOUCH/NAVIGATOR_ZYNQ/ZYNQ_7010_FPGA/top_lcd_touch/top_lcd_touch.srcs/constrs_1/new/top_lcd_touch.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_lcd_touch -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_lcd_touch.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_lcd_touch_utilization_synth.rpt -pb top_lcd_touch_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
