# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/CAO/dds_navigator/7010/dds/dds.cache/wt [current_project]
set_property parent.project_path E:/CAO/dds_navigator/7010/dds/dds.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/CAO/dds_navigator/7010/dds/dds.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/CAO/dds_navigator/7010/dds/doc/rom_400x8b.coe
read_verilog -library xil_defaultlib {
  E:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/new/ad_weave_rec.v
  E:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/new/da_wave_send.v
  E:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/new/key_debounce.v
  E:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/new/dds.v
}
read_ip -quiet E:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/rom_400x8b/rom_400x8b.xci
set_property used_in_implementation false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/rom_400x8b/rom_400x8b_ooc.xdc]

read_ip -quiet E:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/CAO/dds_navigator/7010/dds/dds.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/CAO/dds_navigator/7010/dds/dds.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files E:/CAO/dds_navigator/7010/dds/dds.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top dds -part xc7z010clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dds.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dds_utilization_synth.rpt -pb dds_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
