set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports seg_led_t[0]]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports seg_led_t[1]]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports seg_led_t[2]]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports seg_led_t[3]]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports seg_led_t[4]]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports seg_led_t[5]]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports seg_led_t[6]]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports seg_led_t[7]]

set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports sel_t[0]]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports sel_t[1]]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports sel_t[2]]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports sel_t[3]]

set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports key_row[0]]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports key_row[1]]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports key_row[2]]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports key_row[3]]

set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports key_col[0]]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports key_col[1]]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports key_col[2]]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports key_col[3]]

set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports led[0]]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports led[1]]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports led[2]]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports led[3]]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports led[4]]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports led[5]]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports led[6]]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports led[7]]

set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports swi[0]]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports swi[1]]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports swi[2]]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports swi[3]]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports swi[4]]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports swi[5]]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports swi[6]]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports swi[7]]